### ISSUE TITLE
ha-bestway is not a valid add-on repository

### ISSUE THREAD

**Issue by RaySnel** [cdpuk/ha-bestway#14]
https://github.com/cdpuk/ha-bestway is not a valid add-on repository when trying to add to HACS

![image](https://user-images.githubusercontent.com/58810377/230955078-6e144b56-0564-4e36-b842-bec9a02052ae.png)

**Comment by cdpuk** [comment]
The HACS installation steps can be found here, and are still working for me.
https://hacs.xyz/docs/faq/custom_repositories

Can you describe the steps to reproduce the issue?
