### ISSUE TITLE
HA Integration problems

### ISSUE THREAD

**Issue by Tarnakarlslund** [cdpuk/ha-bestway#17]
When i try to install the Bestway Smart Home App with the custom repository in HA and i check the EU square i get "user does not exists".
when i tryed to switch to the US square the integration did install.
Can it be so nice and perfect so after brexit the englishmen did also get kicked out from the Bestway App *lol*

**Comment by cdpuk** [comment]
Struggling to pick out any issues with the integration from this - please add more detail and reopen if I'm missing something.
