### ISSUE TITLE
Timer settings

### ISSUE THREAD

**Issue by albialbi** [cdpuk/ha-bestway#22]
Is it possible to set timer and activate it?

**Comment by cdpuk** [comment]
Not at present. If someone can work out how to do it, great, but it's not something I plan on adding. I recommend using Home Assistant automations to achieve the same thing.

**Comment by Jogge** [comment]
I have used HomeKit Bridge to make my spa entities available in Apple HomeKit. I'm using an iPad as HomeKit hub.

Then I just say "Hi Siri, turn on spa in 2 hours", or "Hi Siri, turn off filter in 6 hours" whenever I add Chlorine.

I'm also using the following automation to start the filter for 5 minutes every 30 minutes:

![billede](https://github.com/cdpuk/ha-bestway/assets/15981279/7d5e72d1-2008-4917-bfb3-e19dc039d2c3)
