### ISSUE TITLE
Support Smart Touch Wifi Filter Pump

### ISSUE THREAD

**Issue by phretor** [cdpuk/ha-bestway#23]
Hi! I can successfully onboard with my Bestway app credentials, but it looks like the integration is only for SPAs and not Bestway products in general, because I can't see the pump device I see in my app screen.

Is it the integration or the Bestway Cloud API doesn't expose anything else than SPAs?

**Comment by cdpuk** [comment]
I don't own any other Bestway products besides a Lay-Z-Spa, and the API is undocumented, so someone would need to do the reverse engineering to see how the Bestway product range works. If anyone can do some initial investigations and post back here I'd welcome a discussion on where to take it next.

At present, the integration is certainly not designed to cope with anything but spa systems, and even then newer spa products seem to be coming out that communicate in different ways.

**Comment by phretor** [comment]
I’ll do some reversing on my product and let you know!

**Comment by phretor** [comment]
I tested the above with this device and I'm able to power it ON/OFF and set filter timeout in hours. I also added status report when the device reports that a filter change is required.

https://bestwayusa.com/flowclear-smart-touch-wifi-2-000-gal-app-controlled-filter-pump-58614e

**Comment by cdpuk** [comment]
@phretor Please could you try this branch?
https://github.com/cdpuk/ha-bestway/tree/generic-bestway

This is a significant rewrite to make it easier to support a range of devices beyond Airjet spas, and may become v2.0.0 of the integration. As I have no way to test with a pump, your help would be much appreciated.

**Comment by phretor** [comment]
On it!
