### ISSUE TITLE
All devices are diabled and can't enabled

### ISSUE THREAD

**Issue by Skarhand** [cdpuk/ha-bestway#30]
Hello,
I cant' enable any Bestway devices on my system. There ist an error in the Logbook that says, the device is not available.
In the Log I found this:

ERROR (MainThread) [custom_components.bestway.bestway] Unexpected missing key ''system_err1'' while decoding device attributes {"E19": 0, "E18": 0, "E32": 0, "E31": 0, "E30": 0, "E11": 0, "E10": 0, "E13": 0, "E12": 0, "E15": 0, "E14": 0, "E17": 0, "E16": 0, "word5": 100, "word4": 0, "word7": 29, "word6": 0, "word1": 0, "word0": 0, "E29": 0, "word2": 100, "option6": 10244, "ver": 982, "E22": 0, "jet": 0, "E23": 0, "power": 1, "Tnow": 29, "option7": 10260, "option4": 60, "option5": 27176, "option2": 0, "option3": 30, "option0": 59940, "option1": 59940, "E24": 0, "E25": 0, "E26": 0, "E27": 0, "E20": 0, "E21": 0, "E08": 0, "E09": 0, "E06": 0, "E07": 0, "E04": 0, "E05": 0, "E02": 0, "E03": 0, "E01": 0, "bit7": 0, "heat": 3, "Tunit": 1, "wave": 0, "word3": 0, "Tset": 32, "filter": 2, "E28": 0, "bit6": 0, "bit5": 0, "bit4": 0, "bit3": 0, "bit2": 1}

Is this a bug or am I too stupid?

Sorry for my english, I know it's not the yellow from the egg :-)

**Comment by cdpuk** [comment]
This looks like the same issue as #16. Is this a Hydrojet Pro model?

**Comment by Skarhand** [comment]
It is a hydrojet without pro model...

**Comment by cdpuk** [comment]
That makes sense. The README has just been updated to list supported devices (Hydrojet is not one of them). #16 will fix that if someone is able to fully analyse the new protocol.
