### ISSUE TITLE
device went offline and never recovered

### ISSUE THREAD

**Issue by wyntrblue** [cdpuk/ha-bestway#37]
i have been using an older version of this integration for months (since march-ish) and its worked flawlessly with my lazyspa milan. honestly this integration was the single best thing in the world!

## Bestway device
[lazy spa milan ](https://www.lay-z-spa.co.uk/lay-z-spa-milan-airjet-plus.html?gad=1&gclid=CjwKCAjwr_CnBhA0EiwAci5sitzW4XJ_ToVI4Btat-u3dekbXFijiPr20CX10TauLF7wYwD2NBeegxoCy4kQAvD_BwE)
## Describe the bug

a few days ago i noticed that my automation that sets the spa temp and turns it on stopped working. Upon investigation i noticed that all the entities were offline. I checked for updates to the integration this morning and installed the latest version (1.2.0) this duplicated all my entities but they still show as offline. 

i went ahead and removed all the devices within the integration and confirmed that my username and password were correct in the bestway mobile app.

i then added a new device entered my details and now have 1 device and 11 entities.  (screenshot 1)

if i look at the entities themselves i can see they all have a warning status except for spa connected.  (screenshot 2)

## Logs
looking under logs and searching for bestway im not seeing any logging at all. i have enabled debug logging. 

as i said before this was working perfectly for months. Im guessing something has changed with the spa or the api you call in bestway. happy to get some packet sniffing done or anything else to try and get to the bottom of it. but i would need some direction on how to do it. 

thanks

James
![screenshot 1](https://github.com/cdpuk/ha-bestway/assets/34687690/765ccc81-52d5-4161-93ed-15e9013fbe8c)
![screenshot 2](https://github.com/cdpuk/ha-bestway/assets/34687690/d24f16f6-48e2-492b-9783-6565551e35dc)

**Comment by wyntrblue** [comment]
Morning guys.

so this morning I got up to find my automation was working and the tub was showing as online in HA. 

Very strange behaviour.

**Comment by cdpuk** [comment]
Unfortunately the HTTP API used by the integration seems a bit flaky at times. I think the app uses a websocket connection which explains why the app can seem fine when the integration does not. Anyway, glad to see it working again.
