### ISSUE TITLE
Bad request 502

### ISSUE THREAD

**Issue by paducz** [cdpuk/ha-bestway#40]
## Bestway device

Provide the model of your device. A link to the Bestway product page is sometimes useful.

## Describe the bug

The integratiom has problem to retrieve data via API. Device is not available via HA

**Comment by xlemassacre** [comment]
I think its a problem from  bestway, also have issues with the official app since today

**Comment by paducz** [comment]
You are maybe right, but from my side the offical app is working fine

**Comment by paducz** [comment]
Logger: homeassistant.config_entries
Source: config_entries.py:429
First occurred: 11:14:47 (1 occurrences)
Last logged: 11:14:47

Config entry 'username' for bestway integration not ready yet: Error communicating with API: 500, message='INTERNAL SERVER ERROR', url=URL('https://usapi.gizwits.com/app/bindings'); Retrying in background

**Comment by PieDamen** [comment]
Same here, App seems to be working correctly.

Logger: custom_components.bestway.coordinator
Source: helpers/update_coordinator.py:233
Integration: Bestway (documentation, issues)
First occurred: September 28, 2023 at 4:08:47 PM (3 occurrences)
Last logged: 11:00:32 AM

Error fetching Bestway API data: Error communicating with API:
Error fetching Bestway API data: Error communicating with API: 500, message='INTERNAL SERVER ERROR', url=URL('https://usapi.gizwits.com/app/bindings')

**Comment by bsanya89** [comment]
I have exactly the same issue. Any workaround exist for this problem? From the app I am able to control the spa.

**Comment by paducz** [comment]
It is working now. Somewhere was more than 5 hours outage...closing this issue

**Comment by cdpuk** [comment]
FWIW the difference in behaviour is because the official app uses a different method of communication, so it's possible for that to work while the API used by the integration is having problems.
