### ISSUE TITLE
Heads-up - planned deprecation of constants

### ISSUE THREAD

**Issue by jcallaghan** [cdpuk/ha-bestway#43]
## Version of the custom_component
Latest.

## Bestway device

NA

## Describe the bug

Testing 2024.1 Beta and caught this in the logs about planned deprecation of constants in 2025. Thanks for your work on this integration and HNY!

## Logs

```text

TEMP_FAHRENHEIT was used from bestway, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfTemperature.FAHRENHEIT instead, please create a bug report at https://github.com/cdpuk/ha-bestway/issues

```

**Comment by cdpuk** [comment]
Thanks. I'll be sure to sort that out at some point soon. In any case well before 2025 😄
