### ISSUE TITLE
Entity None (<class 'custom_components.bestway.climate.SpaThermostat'>) implements HVACMode(s)

### ISSUE THREAD

**Issue by holdestmade** [cdpuk/ha-bestway#48]
Version 1.3.1

Getting this in logs after update to HA 2024.2

## Logs

```text

Logger: homeassistant.components.climate
Source: components/climate/__init__.py:354
Integration: Climate (documentation, issues)
First occurred: 12:56:14 pm (1 occurrences)
Last logged: 12:56:14 pm

Entity None (<class 'custom_components.bestway.climate.SpaThermostat'>) implements HVACMode(s): off, heat and therefore implicitly supports the turn_on/turn_off methods without setting the proper ClimateEntityFeature. Please create a bug report at https://github.com/cdpuk/ha-bestway/issues

```

**Comment by roygeraets** [comment]
Same here, multiple entity's. 

Version: 1.4.0

`Entity None (<class 'custom_components.bestway.climate.AirjetSpaThermostat'>) implements HVACMode(s): off, heat and therefore implicitly supports the turn_on/turn_off methods without setting the proper ClimateEntityFeature. Please create a bug report at https://github.com/cdpuk/ha-bestway/issues`
