### ISSUE TITLE
I can not login with eu account

### ISSUE THREAD

**Issue by Klimrekken** [cdpuk/ha-bestway#65]
Hello,

Im trying to login to my best way account but it says my username( email) is not registered.

Been using the bestway app almost a year now. Seperatly from ha

**Comment by TheJim0** [comment]
Try to Connect with US account

**Comment by EvoSems** [comment]
Anyone know how to login with an Australian account? im getting Failed to authenticate. Check your credentials.

**Comment by hearntd** [comment]
Having the same issues, unrecognized account on EU (I live in the UK), it fails almost to quickly, like it doesn't even try and check, when using the US it tries but fails as it's not a US account.

**Comment by cdpuk** [comment]
General advice is always to try both US and EU options on the configuration screen - it's never clear which your account will be associated with. 

For anyone reading this but not aware, you must have a Bestway account - a Lay-Z-Spa account is a different thing and not compatible.

If neither of those tips help, log messages while trying to connect would be useful.

This topic does come up every now and then, but never with a clear reason for the error. I'm beginning to wonder whether there is some other factor at play; perhaps something as basic as special characters in a password. If anyone works this out, please report back.

**Comment by Jimbo222** [comment]
Not directly related to the original question, but could be related.

I only recently (in the last few days) upgraded to the latest 1.6.x version of this integration and had to create a US account to get it connect.  My (UK) EU account that was working fine for 1.3.x and earlier was working fine.  But with 1.6 I would get all the way through to add the spa to HA with the entities created, but would never get any data in HA.
1.6.x worked fine without iss when using a US based account.

Also, as soon as I added the spa to HA, it would go offline in the bestway app - this was in any version of the integration on the EU account.
However, on the US account the Spa remains online in the Bestway app (for 1.6.x at least.  I didn't have a US account with prior versions)
