### ISSUE TITLE
Version shows as 0.0.1 in Home Assistant

### ISSUE THREAD

**Issue by pdecat** [cdpuk/ha-bestway#75]
## Version of the custom_component

1.6.0

## Bestway device

[Bestway Lay-Z-Spa Hydrojet Pro with wifi EU P07033](https://fr.bestway.eu/p/pompe-de-filtration-bestway-pour-layzspa-hydrojet-avec-wifi-eu)

## Describe the bug

Version shows as 0.0.1 in Home Assistant:

![image](https://github.com/user-attachments/assets/411809fa-d7f1-4242-8903-c3b0c4d348da)

This comes from https://github.com/cdpuk/ha-bestway/blob/v1.6.0/custom_components/bestway/manifest.json#L14

## Logs

N/A

**Comment by cdpuk** [comment]
Thanks. I was aware this was mandatory but had never previously spotted it anywhere in the UI. We'll make sure this is set in future versions.
