### ISSUE TITLE
Issues controlling spa

### ISSUE THREAD

**Issue by jeffh0821** [cdpuk/ha-bestway#81]
Version 1.6.1 - 1.6.2

## Bestway device

Airjet V01
by Bestway

## Describe the bug

Service calls for any Bestway services (climate, power, filter, bubbles) not sending and/or being received by Bestway.

Unfortunately, I had to roll back to 1.6.0 in order to get control of my hot tub again. Using version 1.6.1 or 1.6.2 prevented me from actually controlling the spa, although it appeared to properly read the various sensors and states.

I'm happy to upgrade again and grab logs. I wish my python skills were better to help fix this. Alas, my last real programming was Java far too many years ago. Although this may be a good excuse to dig in and see how HA does integrations.

Let me know how I can help. Really like the work you've done here.

## Logs

```text

Will re-update to 1.6.2 and grab some logs.

```

**Comment by JaggedJax** [comment]
I'm not sure if it's related, but I'm recently getting a lot of `502` errors from the Bestway servers starting on Nov 10th. They are transient, but it's often enough for some of my automations to fail.

But I don't see how a transient 502 error could be related to the addon version, and this error still only happens occasionally. Seems more likely the issue I'm seeing is an issue on the BestWay side, but thought I'd report it in case it's related.

    Error requesting Bestway API data: 502, message='Bad Gateway', url='https://usapi.gizwits.com/app/bindings'
    Error requesting Bestway API data: 502, message='Bad Gateway', url='https://usapi.gizwits.com/app/devdata/XXX/latest'

**Comment by bodomenke** [comment]
I have the same 502 since last weekend. I have also seen 500 and 503… see below.
This afternoon I reported this via ticket to Bestway. They sent me instructions how to connect a pool to a WiFi… ;-)

<img width="1079" alt="image" src="https://github.com/user-attachments/assets/9aaa6a26-974b-428f-829f-57679450018e">

**Comment by bodomenke** [comment]
FYI: This is the last hour - constantly connects and disconnects. I have done a rollback to v1.61 now and will see if this improves the situation.

<img width="910" alt="image" src="https://github.com/user-attachments/assets/61bae13a-dfa8-48a2-aa50-2f86ae7fe913">

**Comment by bodomenke** [comment]
So this is the last night after rollback to v1.60
It seems that the issue with constant reconnects is not related to the Bestway addon but to the Bestway backend. 

I have reported already to Bestway. Maybe it helps if others report the issue as well.

<img width="924" alt="image" src="https://github.com/user-attachments/assets/b5b12af4-c3fa-489e-914d-3903499ebc4f">

**Comment by cdpuk** [comment]
As you've spotted, there's not much that can be done by the integration when the server side reports problems on the Bestway side of things.

There have been an awful lot of reports of this in recent months. What's interesting is that I've never seen such errors when using my spa, which on on an EU account. For anyone using a US account, it may be worth trying to re-register with an EU account to see if those servers are more reliable.

**Comment by bodomenke** [comment]
@cdpuk FYI: I am with an EU account on the EU instance (euapi.gitwits.com)…

**Comment by cdpuk** [comment]
The best approach would be to implement fully local control. I believe the Gizwitz protocol enables the app to transparently switch between cloud control and a local protocol when on the same subnet. More research required to do that.
